name: Install ARC Workflow from sh file in secrets

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install ARC
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    env:
      OPENRC: ${{ secrets.OPENRC }}
      OS_PASSWORD_INPUT: ${{ secrets.OS_PASSWORD_INPUT }}
      PRIVATE_KEY_FILE: ${{ secrets.PRIVATE_KEY_FILE }}
      OS_CLOUDS: ${{ secrets.OS_CLOUDS }}
      OS_CLOUD: openstack
      OS_CLIENT_CONFIG_FILE: ./clouds.yaml  
      ARC_INSTALL: ${{ secrets.ARC_SH }}
      PEM_KEY: ${{ secrets.PEM_KEY }}
      SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      SSH_PIV_KEY: ${{ secrets.SSH_PIV_KEY }}
      PROXY_CONFIG: ${{ secrets.PROXY_CONFIG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update -y && sudo apt install python3 python3-venv -y && sudo apt-get install build-essential libssl-dev libffi-dev python3-dev -y


      - name: Create venv
        run: |
          python3 -m venv openstack-venv

      - name: Activate venv
        run: |
          source openstack-venv/bin/activate

      - name: Install pip and OpenStack Client
        run: |
          pip install -U requests && pip install python-openstackclient

      - name: Make .ssh directory 
        run: |
          mkdir ~/.ssh

      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<<y

      - name: Transfer SSH public key to VM
        run: |
          echo "$SSH_PIV_KEY" > ~/.ssh/id_ed25519 && echo "$SSH_PUB_KEY" > ~/.ssh/id_ed25519.pub

      - name: Create clouds.yaml and set cloud variable
        run: |
          echo "$OS_CLOUDS" > $OS_CLIENT_CONFIG_FILE

      - name: Which OpenStack
        run: |
          which openstack

      - name: Check for key existing
        run: |
          echo "KEYEXIST=$(openstack keypair list -c Name | if grep -q "ChiPair"; then echo "true"; else echo "false"; fi)" >> $GITHUB_ENV

      - name: Generate OpenStack KeyPair if needed
        run: |
          if test "$KEYEXIST" = "false"; then openstack keypair create --public-key ~/.ssh/id_ed25519.pub --type ssh ChiPair; else openstack keypair delete ChiPair && openstack keypair create --public-key ~/.ssh/id_ed25519.pub --type ssh ChiPair; fi

      - name: Check for volume existing
        run: |
          echo "VOLEXIST=$(openstack volume list -c Name | if grep -q "TheFarm"; then echo "true"; else echo "false"; fi)" >> $GITHUB_ENV

      - name: Create Boot Volume if needed
        run: |
          if test "$VOLEXIST" = "false"; then openstack volume create --image Ubuntu-22.04 --size 20 --bootable TheFarm; else openstack volume delete TheFarm && openstack volume create --image Ubuntu-22.04 --size 20 --bootable TheFarm; fi

      - name:  Initialise VM Instance
        run: |
          openstack server create --flavor general.v1.small  --volume $(openstack volume show TheFarm -f value -c id) --block-device delete_on_termination=true --key-name ChiPair --network stackhpc-ipv4-geneve --wait OlMacDonaldsFarm

      - name:  Sleep
        run: |
          sleep 1m 30s

      - name: Make sure openssh-server is installed
        run: |
          sudo apt-get install openssh-server -y

      - name: Transfer ARC install script to ARC_INSTALL.sh file
        run: |
          echo "$ARC_INSTALL" > ARC_INSTALL.sh && ls -ltra 

      - name: Transfer KUBECONFIG to .kube/config
        run: |
          mkdir .kube && echo "$KUBECONFIG" > .kube/config

      - name: Assign Secret to variable PRIVATE_KEY_FILE
        run: |
          echo "$PEM_KEY" > PRIVATE_KEY_FILE

#      - name: Transfer SSH public key to VM
#        run: |
#          echo "$SSH_PIV_KEY" > ~/.ssh/id_ed25519 && echo "$SSH_PUB_KEY" > ~/.ssh/id_ed25519.pub

      - name: Generate SSH config file
        run: |
          echo "$PROXY_CONFIG" > ~/.ssh/config 
        #&& chmod 600 ~/.ssh/config && chmod 600 ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519.pub && cat ~/.ssh/config

      - name: Transfer OPENRC to openrc.sh file and then source it
        run: |
          echo "$OPENRC" > openrc.sh &&  echo "$OS_PASSWORD_INPUT" | source openrc.sh

      #- name: Softlink tty to /dev/ttyS0
      #  run: |
      #    echo "console=`tty`" >> $GITHUB_ENV && ln -s $console /dev/tty

      - name: Change chmod of private key
        run: |
          chmod 600 ~/.ssh/id_ed25519 

      - name: scp to VM ARC_INSTALL.sh
        run: |
         eval $(ssh-agent) && ssh-add ~/.ssh/id_ed25519 && scp -v -o StrictHostKeyChecking=no -J sms-bastion ./ARC_INSTALL.sh ubuntu@$(openstack server list --name OlMacDonaldsFarm -c Networks | grep -oE "(\w*[.]+[0-9]{1,3})+"):~/.

      - name: scp to VM .kube/config
        run: |
         eval $(ssh-agent) && ssh-add ~/.ssh/id_ed25519 && scp -r -v -o StrictHostKeyChecking=no -J sms-bastion .kube ubuntu@$(openstack server list --name OlMacDonaldsFarm -c Networks | grep -oE "(\w*[.]+[0-9]{1,3})+"):~/.

      - name: scp to VM PRIVATE_KEY_FILE
        run: |
         eval $(ssh-agent) && ssh-add ~/.ssh/id_ed25519 && scp -v -o StrictHostKeyChecking=no -J sms-bastion PRIVATE_KEY_FILE ubuntu@$(openstack server list --name OlMacDonaldsFarm -c Networks | grep -oE "(\w*[.]+[0-9]{1,3})+"):~/.

      - name: Connect to VM
        run: |
          eval $(ssh-agent) && ssh-add ~/.ssh/id_ed25519 && ssh -o StrictHostKeyChecking=no -J sms-bastion  ubuntu@$(openstack server list --name OlMacDonaldsFarm -c Networks | grep -oE "(\w*[.]+[0-9]{1,3})+")

      #- name: Transfer ARC install script to ARC_INSTALL.sh file
      #  run: |
      #    echo "$ARC_INSTALL" > ARC_INSTALL.sh && ls -ltra 

#      - name: Transfer SSH public key to VM
#        run: |
#          echo "$SSH_PUB_KEY" >> ~/.ssh/authorized_keys

#      - name: make .kube directory
#        run: |
#          mkdir ~/.kube

#      - name: Transfer KUBECONFIG to .kube/config
#        run: |
#          echo "$KUBECONFIG" > ~/.kube/config

      - name: Export KUBECONFIG
        run: |
          eval $(ssh-agent) && ssh-add ~/.ssh/id_ed25519 && ssh -o StrictHostKeyChecking=no -J sms-bastion  ubuntu@$(openstack server list --name OlMacDonaldsFarm -c Networks | grep -oE "(\w*[.]+[0-9]{1,3})+") "KUBECONFIG=~/.kube/config; export KUBECONFIG; chmod +x ARC_INSTALL.sh; ./ARC_INSTALL.sh" 

#      - name: Run ARC_INSTALL.sh
#        run: |
#          chmod +x ARC_INSTALL.sh && ./ARC_INSTALL.sh

#      - name: Disconnect
#        run: |
#          exit

#      - name: Delete VM
#        run: |
#          openstack server delete OlMacDonaldsFarm --wait

#      - name: Delete KeyPair
#        run: |
#          openstack keypair delete ChiPair
